services:
  kali:
    image: ghcr.io/t-yng/kali-linux:latest
    container_name: ctf-kali-linux
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - .:/home/kali/tryhackme
    cap_add: # Add host network privileges to the container
      - NET_RAW
      - NET_ADMIN
    network_mode: host
    working_dir: /home/kali/tryhackme
